"""主题讲义：以中学教师视角为每个主题写的结构化总结。

原则：简洁、好记、有例子（例句由 /taxonomy 从教材语料自动提取，
尽力使用教材原文，见 Query.taxonomy 的 examples 字段）。

统一讲解形式：
  summary  一句话定位（这个主题考什么）
  points   核心规则条目（3-6 条，每条一行，公式化表述）
  formula  构成公式（可直接背）
  mnemonic 记忆口诀（可选）
  tips     常考易错点（1-3 条）
"""

THEME_NOTES: dict[tuple[str, str], dict] = {
    # ------------------------------------------------------------------ 词法
    ("词法", "名词"): {
        "summary": "名词考三件事：可数不可数、复数怎么变、所有格怎么加。",
        "points": [
            "可数名词有单复数（book→books）；不可数名词无复数（water, music, advice）",
            "复数规则：一般 +s；s/x/ch/sh/o 结尾 +es；辅音+y → ies；f/fe → ves",
            "不规则复数必背：man→men, woman→women, child→children, foot→feet, tooth→teeth",
            "所有格：有生命 +'s（Tom's）；无生命用 of（the door of the room）",
            "专有名词（人名/地名）首字母大写，通常不加冠词",
        ],
        "formula": "复数：+s ｜ s,x,ch,sh,o +es ｜ 辅+y→ies ｜ f/fe→ves ｜ 不规则单独背",
        "mnemonic": "「黑人英雄爱吃土豆西红柿」— negro/hero/Potato/tomato 都 +es",
        "tips": ["不可数名词误加复数是高频错点（informations ❌）"],
    },
    ("词法", "代词"): {
        "summary": "代词考代换是否正确：主格/宾格/形容词性物主/名词性物主/反身，五张表要分清。",
        "points": [
            "主格作主语（I/he/she/they），宾格作宾语（me/him/her/them）",
            "形容词性物主代词必须接名词（my book）；名词性物主单独用（The book is mine）",
            "反身代词：myself/yourself/himself…，主宾同人或强调时用",
            "it 作形式主语/形式宾语：It is important to learn English.",
            "不定代词（something/anybody/nobody）作主语时谓语用三单",
        ],
        "formula": "主格-宾格-形物-名物-反身 五位一体成对记：I-me-my-mine-myself",
        "mnemonic": "「有名则形，无名则名」——后面有名词用形容词性（my），没有名词用名词性（mine）",
        "tips": ["something 用于肯定句，anything 用于否定/疑问句"],
    },
    ("词法", "冠词"): {
        "summary": "冠词考 a/an/the/零冠词四选一，核心是「特指用 the，泛指用 a/an」。",
        "points": [
            "a 辅音音素前，an 元音音素前（an hour, a university——看读音不看字母）",
            "the 表特指：双方都知道的、第二次提到的、独一无二的事物（the sun）",
            "零冠词：球类运动（play football）、三餐（have lunch）、专有名词前",
            "乐器前要加 the（play the piano）；学科前不加（study English）",
            "a/an + 序数词表「再一、又一」（a second time 又一次）",
        ],
        "formula": "特指 the ｜ 泛指单数 a/an ｜ 复数/不可数泛指零冠词",
        "mnemonic": "「特指用 the，泛指 a/an；三餐球类零冠词，西洋乐器要加 the」",
        "tips": ["an hour / an honest boy：h 不发音按元音算"],
    },
    ("词法", "数词"): {
        "summary": "数词考分数表达、hundred/thousand 的单复数、序数词。",
        "points": [
            "基数词表数量，序数词表顺序（one→first, two→second, three→third）",
            "hundred/thousand/million 前有具体数字时不加 s（three hundred ✓）",
            "表「成百上千」用复数 + of：hundreds of, thousands of",
            "分数：分子基数词、分母序数词，分子>1 分母加 s（two thirds）",
            "「半个」a half，「一个半」one and a half + 复数名词",
        ],
        "formula": "具体数字 + hundred（无 s）｜ hundreds of（有 of 必有 s）",
        "mnemonic": "「有数字不加 s，有 of 必加 s」",
        "tips": ["two-thirds of the students 后谓语用复数（students 决定）"],
    },
    ("词法", "介词"): {
        "summary": "介词考时间/地点用 in-on-at 的选择，以及固定搭配。",
        "points": [
            "时间：大用 in（年/月/季节），中用 on（具体某天），小用 at（时刻）",
            "地点：in 大地方（城市/国家），on 表面，at 小地点/点位",
            "above 与 over：above 只表上方，over 还有「覆盖/越过」义",
            "between（两者）与 among（三者以上）",
            "by + 交通工具中间不加冠词：by bus / by bike / by plane",
        ],
        "formula": "时间：in 年月季、on 日、at 时刻 ｜ 地点：in 大 on 面 at 点",
        "mnemonic": "「大年月季用 in，具体某天用 on，几点几分用 at」",
        "tips": ["in the tree（外物）与 on the tree（树上长的）之分"],
    },
    ("词法", "连词"): {
        "summary": "连词考并列连词的选择（and/or/but/so）与成对连词的前后一致。",
        "points": [
            "并列：and（顺承）、or（否则/选择）、but（转折）、so（因果）",
            "both…and（两者都），either…or（任一），neither…nor（都不）",
            "either…or / neither…nor 就近原则：谓语与最近主语一致",
            "though/although 不与 but 连用（中文习惯直译是错的）",
            "because 不与 so 连用（同一句只用一个）",
        ],
        "formula": "both…and 谓语复数 ｜ either…or / neither…nor 就近一致",
        "mnemonic": "「因为 because 不配 so，虽然 though 不配 but」",
        "tips": ["Not only you but also he ___ → 用 is（就近 he）"],
    },
    ("词法", "形容词与副词"): {
        "summary": "形容词副词考比较级/最高级的变化规则与句型，以及两类词的分工。",
        "points": [
            "形容词修饰名词（a beautiful girl）；副词修饰动词/形容词（run quickly）",
            "比较级：单音节 +er/est（tall→taller→tallest）",
            "多音节 more/most（more interesting，❌interestinger）",
            "不规则必背：good→better→best, bad→worse→worst, far→farther→farthest",
            "句型：比较级 + than；the + 最高级 + in/of 范围",
            "as…as 中间用原级（as tall as）；not so…as 表不如",
        ],
        "formula": "比较级 than ｜ 最高级 the…in/of ｜ as…as 用原级",
        "mnemonic": "「单音节加 er，多音节加 more，good 变 better 记心头」",
        "tips": ["much/a lot/far/even 可修饰比较级（much better），very 只修饰原级"],
    },
    ("词法", "动词"): {
        "summary": "动词考种类辨析（实义/系/助/情态）与短语动词。",
        "points": [
            "实义动词有完整词义；系动词接形容词（look/sound/feel/taste/smell + adj.）",
            "助动词（do/be/have）只帮助构成时态/否定/疑问，无词义",
            "短语动词：look after 照顾 / look for 寻找 / look forward to 期待",
            "及物动词直接接宾语；不及物需介词（listen to, arrive at/in）",
            "感官动词 see/hear/watch + 宾语 + do（全过程）/ doing（进行中）",
        ],
        "formula": "系动词 + 形容词（不用副词）：The flower smells nice.",
        "mnemonic": "「听起来 look/sound/feel/taste/smell 都是系，后面形容词别用副」",
        "tips": ["see sb do 与 see sb doing 的区别是必考点"],
    },
    ("词法", "情态动词"): {
        "summary": "情态动词考「后接动词原形」与各词的功能含义。",
        "points": [
            "情态动词后一律接动词原形（can swim ✓，can to swim ❌）",
            "can 能力/许可；must 必须（否定 needn't 不必）；may 可以/可能",
            "must 表推测：肯定句 must，否定句 can't（不可能是 mustn't ❌）",
            "should 应该（建议）；had better 最好（had better do）",
            "would like to do = want to do（礼貌表达）",
        ],
        "formula": "情态动词 + do（原形）｜ must 的否定回答用 needn't",
        "mnemonic": "「must 问 needn'答，推测否定 can't 搭」",
        "tips": ["—Must I…? —No, you needn't.（不用 mustn't）"],
    },
    # ------------------------------------------------------------------ 时态
    ("时态", "一般现在时"): {
        "summary": "一般现在时考三单变化与「经常性动作/客观真理」的判定。",
        "points": [
            "构成：主语 + V原形；三单 +s/es（he plays）",
            "用法①：经常性/习惯性动作（常伴 always/usually/often/every day）",
            "用法②：客观真理（The earth goes around the sun.）",
            "三单变化：+s；s/x/ch/sh/o +es；辅+y → ies（study→studies）",
            "否定/疑问借 do/does：He doesn't play. Does he play?",
        ],
        "formula": "三单：+s ｜ s,x,ch,sh,o +es ｜ 辅+y→ies",
        "mnemonic": "「经常往往 every 天，一般现在三单变」",
        "tips": ["时间/条件状语从句中用一般现在时表将来（主将从现）"],
    },
    ("时态", "一般过去时"): {
        "summary": "一般过去时考规则/不规则动词过去式与明确过去时间标志。",
        "points": [
            "构成：主语 + V-ed（规则）/ 不规则过去式",
            "标志词：yesterday, last week/year, …ago, in 2020, just now",
            "规则变化：+ed；e 结尾 +d；辅+y → ied；重读闭音节双写 +ed（stop→stopped）",
            "不规则必背：go→went, see→saw, buy→bought, take→took",
            "否定/疑问借 did，动词还原：He didn't go. Did he go?",
        ],
        "formula": "did 出现，动词还原（did 后面用原形）",
        "mnemonic": "「yesterday 站岗，动词穿 ed 装」",
        "tips": ["did 已表过去，再加 went 是双重过去（didn't went ❌）"],
    },
    ("时态", "一般将来时"): {
        "summary": "一般将来时考 will 与 be going to 的选择。",
        "points": [
            "构成：will + 动词原形（各人称通用）",
            "be going to：计划好的/有迹象的事；will：临时决定/预测",
            "标志词：tomorrow, next week/year, soon, in + 时间段",
            "there be 将来时：There will be / There is going to be",
            "祈使句 + and/or + will：Work hard, and you will pass.",
        ],
        "formula": "will + do ｜ be going to + do（计划性更强）",
        "mnemonic": "「明天下周和 soon，will 加原形记心中」",
        "tips": ["in three days 表「三天后」用将来时"],
    },
    ("时态", "现在进行时"): {
        "summary": "现在进行时考 be + doing 的构成与现在/近期动作的判定。",
        "points": [
            "构成：am/is/are + V-ing",
            "标志词：now, right now, Look! Listen! at the moment",
            "ing 变化：一般 +ing；e 结尾去 e（make→making）；重读闭音节双写（run→running）",
            "表示近期安排：We are leaving tomorrow.（位移动词可表将来）",
            "状态动词（know/love/like/believe）一般不用进行时",
        ],
        "formula": "be + doing ｜ Look/Listen 一出现，进行时跑不了",
        "mnemonic": "「Look！Listen！now 在场，be 加 doing 进行忙」",
        "tips": ["I'm knowing him ❌（know 是状态动词）"],
    },
    ("时态", "过去进行时"): {
        "summary": "过去进行时考「过去某时正在进行」与 when/while 的搭配。",
        "points": [
            "构成：was/were + V-ing",
            "标志词：at that time, at 8 last night, the whole morning",
            "when + 一般过去时（短暂动作）interrupt 进行时：I was reading when he came.",
            "while + 进行时（延续动作）对比：While I was reading, he was cooking.",
            "常与 when/while 连用考「长动作背景 + 短动作打断」",
        ],
        "formula": "was/were + doing ｜ when 打断 while 陪伴",
        "mnemonic": "「while 两长相对望，when 短闯长景中」",
        "tips": ["when 从句用进行时还是过去时看动作长短"],
    },
    ("时态", "现在完成时"): {
        "summary": "现在完成时考 have/has + done 与「过去发生、现在有影响」的核心概念。",
        "points": [
            "构成：have/has + 过去分词",
            "标志词：already, just, yet, ever, never, so far, recently",
            "延续性时间：for + 时间段 / since + 时间点（与可延续动词连用）",
            "have been to（去过已回）与 have gone to（去了未回）",
            "瞬间动词（buy/die/come）不能与 for/since 连用（have had ✓ have bought for ❌）",
        ],
        "formula": "have/has + done ｜ for 段 since 点，动词要能延",
        "mnemonic": "「already 肯定 yet 疑否，for 接段来 since 接点」",
        "tips": ["have gone to 与 have been to 之分是高频考点"],
    },
    ("时态", "过去完成时"): {
        "summary": "过去完成时考「过去的过去」，必须有更近的过去动作作参照。",
        "points": [
            "构成：had + 过去分词",
            "核心：发生在另一过去动作之前（By the time…, When…+过去时）",
            "标志：by the time, by + 过去时间, before, after",
            "常见句式：By the time we arrived, the train had left.",
            "宾语从句主过从过：He said he had finished it.",
        ],
        "formula": "had + done ｜ 先发生的事用 had，过去的过去",
        "mnemonic": "「一过二过先分清，先动作用 had 行」",
        "tips": ["单独一个过去动作不能配 had，必须有参照"],
    },
    ("时态", "过去将来时"): {
        "summary": "过去将来时考「从过去看将来」：would + do。",
        "points": [
            "构成：would + 动词原形（will 的过去式）",
            "主要用于宾语从句：主句过去时，从句将来 → would",
            "He said he would come the next day.",
            "was/were going to do 也可表过去将来（计划）",
            "时间基准词变化：tomorrow→the next day, next week→the next week",
        ],
        "formula": "would + do ｜ 主过从将 would 连",
        "mnemonic": "「主句过去从句将，will 摇身变 would」",
        "tips": ["直接引语变间接引语时时态后移一级"],
    },
    ("时态", "动词时态综合"): {
        "summary": "综合考「看标志词定时态」与从句时态呼应两条主线。",
        "points": [
            "做题第一步：圈时间标志词（yesterday/now/tomorrow/so far）",
            "无标志词看语境：影响现在用完成时，背景长动作用进行时",
            "从句时态三条铁律：主将从现、主过从必过、真理永一现",
            "注意并列结构时态一致：He got up and went out.",
        ],
        "formula": "先找标志词 → 再看主从句 → 最后定谓语",
        "mnemonic": "「主将从现，主过从过，真理永现」",
        "tips": ["so far / by now = 现在完成时；by + 过去时点 = 过去完成时"],
    },
    # ------------------------------------------------------------------ 语态
    ("语态", "被动语态"): {
        "summary": "被动语态考 be + done 的时态变化与主动改被动的两步法。",
        "points": [
            "构成：be + 过去分词（时态体现在 be 上）",
            "一般现在被动：am/is/are done；一般过去：was/were done",
            "含情态动词：must/can + be done（情态后 be 用原形）",
            "主动变被动两步：宾语提前作主语，动词变 be done（by 施动者）",
            "不及物动词（happen, arrive, rise）无被动",
        ],
        "formula": "be + done ｜ 情态 + be done ｜ 进行 be being done",
        "mnemonic": "「主语是受事，be 加过去分词时态变」",
        "tips": ["must be finished ✓ must been finished ❌（情态后 be 原形）"],
    },
    # ------------------------------------------------------------------ 非谓语
    ("非谓语", "不定式"): {
        "summary": "不定式考 to do 的三大功能与「省 to」口诀。",
        "points": [
            "作宾语：want/decide/hope/plan + to do",
            "作宾补：ask/tell/want sb to do",
            "作目的状语：He came to see me.（为了）",
            "省 to 口诀：一感二听三让四看半帮助——feel, hear/listen to, let/make/have, see/watch/look at, help (to)",
            "疑问词 + to do：I don't know what to do.",
        ],
        "formula": "want sb to do ｜ make sb do（省 to）｜ 被动还原 to：be made to do",
        "mnemonic": "「一感二听三让四看半帮助，主动省 to 被动补」",
        "tips": ["主动 let/make sb do，被动必须 be made to do"],
    },
    ("非谓语", "动名词"): {
        "summary": "动名词考 doing 作主语/宾语与「只接 doing 的动词」清单。",
        "points": [
            "作主语谓语用三单：Swimming is fun.",
            "介词后必须用 doing：be good at swimming",
            "只接 doing 的动词：enjoy, finish, practice, mind, keep, suggest",
            "短语接 doing：can't help doing, be worth doing, look forward to doing",
            "既接 to do 又接 doing 意义不同：stop to do（停下来去做）/ stop doing（停止做）",
        ],
        "formula": "enjoy/finish/practice/mind/keep + doing ｜ to 是介词后接 doing",
        "mnemonic": "「喜欢享受又完成，练习介意保持 suggest」",
        "tips": ["look forward to 的 to 是介词，必须接 doing"],
    },
    # ------------------------------------------------------------------ 句法
    ("句法", "宾语从句"): {
        "summary": "宾语从句考三件事：引导词、语序、时态。",
        "points": [
            "引导词：that（陈述，可省）；if/whether（一般疑问）；特殊疑问词",
            "语序铁律：从句一律陈述语序（I don't know where he lives ❌ where does he live）",
            "时态：主过从必过；主现从不限；真理永一现",
            "could you tell me… 中 could 是委婉不是过去，从句按实际时态",
            "宾语从句的否定转移：I think he isn't… → I don't think he is…",
        ],
        "formula": "引导词 + 主语 + 谓语（陈述语序）",
        "mnemonic": "「宾语从句三关：连词、语序、时态」",
        "tips": ["Do you know where he lives? 不能用倒装语序"],
    },
    ("句法", "状语从句"): {
        "summary": "状语从句考连词选择与「主将从现」。",
        "points": [
            "时间：when/while/as/before/after/until/as soon as",
            "条件：if（如果）/unless（除非）",
            "原因：because/since/as；结果：so…that/such…that",
            "让步：though/although/even if",
            "铁律：时间/条件状语从句用一般现在时表将来（主将从现）",
        ],
        "formula": "If/When + 现在时，主句 will + do",
        "mnemonic": "「主将从现——主句将来，从句现在」",
        "tips": ["as soon as / not…until 也遵循主将从现"],
    },
    ("句法", "定语从句"): {
        "summary": "定语从句考关系代词选择（who/which/that/whose）与只能用 that 的场景。",
        "points": [
            "先行词是人用 who/that；物用 which/that",
            "whose 表所属：the boy whose father is a doctor",
            "只能用 that：先行词是 everything/nothing/all/序数词/最高级修饰时",
            "关系代词作宾语可省：the book (that) I bought",
            "关系副词：when（时间）/where（地点）/why（原因）",
        ],
        "formula": "人 who，物 which，都能 that；作宾可省略",
        "mnemonic": "「先行不定代，that 走天下」",
        "tips": ["who 作主语时谓语与先行词保持一致"],
    },
    ("句法", "主谓一致"): {
        "summary": "主谓一致考三原则：语法一致、意义一致、就近一致。",
        "points": [
            "语法一致：单数主语三单；and 连接两个主语用复数",
            "就近原则：either…or / neither…nor / not only…but also——谓语靠近哪个主语",
            "就远原则：with/together with/along with 不影响前面主语",
            "不可数名词/动名词/不定式作主语用三单",
            "the number of…（…的数量）用单数；a number of…（许多）用复数",
        ],
        "formula": "either…or 就近 ｜ with 附加就远 ｜ the number 单 a number 复",
        "mnemonic": "「就近 or，就远 with，the number 单数记心里」",
        "tips": ["Tom with his friends ___ playing → is（就远）"],
    },
    ("句法", "感叹句"): {
        "summary": "感叹句考 What 与 How 的选择——中心词是名词还是形容词/副词。",
        "points": [
            "What + (a/an) + 形容词 + 名词：What a beautiful day!",
            "How + 形容词/副词：How beautiful the day is!",
            "判断法：感叹部分中心是名词用 What，是形容词/副词用 How",
            "不可数/复数名词不加 a：What fine weather! What tall trees!",
            "其余成分保持陈述语序（主语 + 谓语在后面）",
        ],
        "formula": "What + n. 短语！ ｜ How + adj./adv.！",
        "mnemonic": "「有名用 what，无名用 how；可数单数 a 来搭」",
        "tips": ["What fine weather! 不加 a（weather 不可数）"],
    },
    ("句法", "反义疑问句"): {
        "summary": "反义疑问句考「前肯后否、前否后肯」与四大特殊情形。",
        "points": [
            "基本式：前肯后否，前否后肯；时态/人称与前句一致",
            "否定词（never/hardly/little/few）算否定 → 后半用肯定",
            "I am… → aren't I?",
            "Let's… → shall we?（Let us… → will you?）",
            "There be → be + there：There is a book, isn't there?",
            "祈使句 → will you?",
        ],
        "formula": "前肯后否 · 前否后肯 · 否定词反着算",
        "mnemonic": "「我变 aren't I，Let's 配 shall，there be 借 there」",
        "tips": ["hardly/never 出现时后半句必须用肯定"],
    },
    ("句法", "特殊疑问句"): {
        "summary": "特殊疑问句考疑问词选择（what/who/where/when/how 系列）。",
        "points": [
            "what 事物；who 人；whose 谁的；which 哪个（有范围）",
            "where 地点；when 时间；why 原因",
            "how 系列：how old 年龄 / how many 可数多少 / how much 不可数/价格 / how often 频率 / how long 时长",
            "语序：疑问词 + 一般疑问句（对主语提问除外）",
            "对主语提问语序不变：Who broke the window?",
        ],
        "formula": "疑问词 + 助动词 + 主语 + 原形（对主语提问直接陈述语序）",
        "mnemonic": "「多少可数 many 配，不可数价格 much 随；频率 often 长度 long」",
        "tips": ["how many + 复数名词，how much + 不可数名词"],
    },
    ("句法", "倒装句"): {
        "summary": "倒装句考 so/neither 的部分倒装与常见完全倒装。",
        "points": [
            "So + 助/be/情态 + 主语：「某人也是」（肯定）",
            "Neither/Nor + 助/be/情态 + 主语：「某人也不」（否定）",
            "So + 主语 + 助动词：「确实如此」（赞同，不倒装）",
            "完全倒装：Here comes the bus. / There goes the bell.",
            "Only + 状语置于句首，主句部分倒装：Only then did I know.",
        ],
        "formula": "So/Neither + 助动词 + 主语（倒装）；两句话题才倒装",
        "mnemonic": "「也是 so，也不 neither，后面助动词提前跑」",
        "tips": ["So he does（确实如此）与 So does he（他也是）之分必考"],
    },
}


# 固定搭配清单：table 字段为分类搭配表（模式 | 释义），前端渲染为速查表
THEME_NOTES[("固定搭配", "动词固定搭配")] = {
    "summary": "动词搭配考三张清单：接 sb do（省 to）、接 to do、接 doing，外加双义搭配辨析。",
    "points": [
        "判断口诀：看见 make/let/see/hear/watch 接 sb，后面动词用原形",
        "want/ask/tell/decide/hope 等 + to do；enjoy/finish/practice/mind/keep + doing",
        "look forward to / be used to / be worth 的 to 是介词，必须接 doing",
        "双义搭配必考：stop to do（停下来去做另一事）≠ stop doing（停止正在做的事）",
    ],
    "formula": "省 to 口诀：一感二听三让四看半帮助（feel; hear/listen to; let/make/have; see/watch/look at; help）",
    "mnemonic": "「喜欢享受又完成，练习介意保持 suggest——后面全接 doing」",
    "tips": ["主动 make sb do，被动必须 be made TO do（还原 to）"],
    "table": [
        {"cat": "动词 + sb + do（省 to）", "items": [
            ["make sb. do sth.", "让某人做某事"], ["let sb. do sth.", "让某人做某事"],
            ["have sb. do sth.", "叫某人做某事"], ["see sb. do/doing", "看见某人做/正在做"],
            ["hear sb. do/doing", "听见某人做/正在做"], ["watch sb. do/doing", "观看某人做/正在做"],
            ["feel sb. do", "感觉到某人做"], ["help sb. (to) do", "帮助某人做"],
        ]},
        {"cat": "动词 + sb + to do", "items": [
            ["ask sb. to do", "叫某人做"], ["tell sb. to do", "告诉某人做"],
            ["want sb. to do", "想要某人做"], ["allow sb. to do", "允许某人做"],
            ["invite sb. to do", "邀请某人做"], ["teach sb. to do", "教某人做"],
            ["advise sb. to do", "建议某人做"], ["warn sb. not to do", "警告某人别做"],
        ]},
        {"cat": "动词 + to do", "items": [
            ["want to do", "想要做"], ["decide to do", "决定做"], ["hope to do", "希望做"],
            ["plan to do", "计划做"], ["agree to do", "同意做"], ["refuse to do", "拒绝做"],
            ["learn to do", "学会做"], ["offer to do", "主动提出做"],
            ["promise to do", "承诺做"], ["can't wait to do", "迫不及待做"],
            ["would like to do", "愿意做"], ["It takes sb. time to do", "花某人时间做"],
        ]},
        {"cat": "动词 + doing", "items": [
            ["enjoy doing", "喜欢做"], ["finish doing", "完成做"], ["practice doing", "练习做"],
            ["mind doing", "介意做"], ["keep doing", "保持做"], ["suggest doing", "建议做"],
            ["avoid doing", "避免做"], ["can't help doing", "禁不住做"],
            ["feel like doing", "想要做"], ["be worth doing", "值得做"],
            ["be busy doing", "忙于做"], ["look forward to doing", "期待做"],
            ["be used to doing", "习惯于做"], ["spend...(in) doing", "花费…做"],
        ]},
        {"cat": "双义搭配（to do ≠ doing）", "items": [
            ["stop to do / stop doing", "停下来去做 / 停止做"],
            ["remember to do / doing", "记得要去做（未做）/ 记得做过"],
            ["forget to do / doing", "忘记要做 / 忘记做过"],
            ["try to do / doing", "努力做 / 尝试做"],
            ["go on to do / doing", "接着做另一事 / 继续做同一事"],
        ]},
        {"cat": "常用动词短语", "items": [
            ["had better do", "最好做"], ["would rather do", "宁愿做"],
            ["why not do", "为什么不做"], ["put on / take off", "穿上 / 脱下"],
            ["turn on / turn off", "打开 / 关闭"], ["give up doing", "放弃做"],
            ["pick up", "捡起；接人"], ["look after", "照顾"], ["look for", "寻找"],
            ["look up", "查阅"], ["get on / get off", "上/下车"], ["wake up", "醒来"],
            ["grow up", "长大"], ["come true", "实现"], ["take part in", "参加"],
            ["catch up with", "赶上"], ["make friends with", "与…交朋友"],
        ]},
    ],
}

THEME_NOTES[("固定搭配", "介词固定搭配")] = {
    "summary": "介词搭配考 be + 形容词 + 介词 与动词 + 介词 两张清单，接错介词全句错。",
    "points": [
        "be + adj + prep 固定：be good at / be interested in / be afraid of",
        "动词 + 宾语 + 介词：take care of / pay attention to / catch up with",
        "近义介词对比：listen to（听）vs hear（听见）；look at（看）vs see（看见）",
        "arrive at 小地点 / arrive in 大地点",
    ],
    "formula": "at 小 in 大（arrive）；for 为了（wait/pay/ask）；of 所属（take care/be full）",
    "mnemonic": "「善于 good at，感兴趣 interested in，害怕 afraid of」",
    "tips": ["be made of（看得出原料）/ be made from（看不出原料）之分必考"],
    "table": [
        {"cat": "be + 形容词 + 介词", "items": [
            ["be good at", "擅长于"], ["be interested in", "对…感兴趣"],
            ["be afraid of", "害怕"], ["be proud of", "为…自豪"],
            ["be full of", "充满"], ["be late for", "迟到"],
            ["be different from", "与…不同"], ["be famous for", "因…出名"],
            ["be angry with sb.", "生某人的气"], ["be worried about", "担心"],
            ["be strict with sb.", "对某人严格"], ["be surprised at", "对…惊讶"],
            ["be friendly to", "对…友好"], ["be kind to", "对…和善"],
        ]},
        {"cat": "动词 + 介词", "items": [
            ["listen to", "听"], ["look at", "看"], ["look for", "寻找"],
            ["wait for", "等待"], ["pay for", "付款"], ["ask for",  "请求"],
            ["agree with", "同意（某人）"], ["depend on", "依靠"],
            ["belong to", "属于"], ["hear from", "收到…来信"],
            ["hear of", "听说"], ["laugh at", "嘲笑"],
            ["learn from", "向…学习"], ["think about / of", "思考 / 想起"],
            ["worry about", "担心"], ["spend...on", "在…花费"],
            ["thank...for", "因…感谢"], ["arrive at / in", "到达（小/大地点）"],
            ["get on with", "与…相处"], ["talk about", "谈论"],
        ]},
        {"cat": "动词 + 宾语 + 介词", "items": [
            ["take care of", "照顾"], ["pay attention to", "注意"],
            ["look forward to", "期待"], ["catch up with", "赶上"],
            ["get on well with", "与…相处融洽"], ["make fun of", "取笑"],
            ["say goodbye to", "向…告别"], ["say hello to", "向…问好"],
            ["take pride in", "以…为荣"], ["make use of", "利用"],
        ]},
        {"cat": "其他高频介词短语", "items": [
            ["borrow...from", "向…借"], ["lend...to", "把…借给"],
            ["be made of / from", "由…制成（看得出/看不出原料）"],
            ["be made in", "在…制造"], ["on one's way to", "在去…的路上"],
            ["in front of / in the front of", "在…前面（外部/内部）"],
            ["at the end of", "在…末尾"], ["by the way", "顺便说"],
            ["in a hurry", "匆忙"], ["on time / in time", "按时 / 及时"],
        ]},
    ],
}

THEME_NOTES[("固定搭配", "固定句型")] = {
    "summary": "固定句型考结果、程度、并列三大系列，认出句型直接套结构。",
    "points": [
        "结果句型：so + adj + that / such + n + that / too...to / enough to",
        "并列句型：both...and（复数谓语）；either...or / neither...nor（就近）",
        "It 句型：It is adj for/of sb to do；It takes sb time to do",
        "越…越…：the + 比较级, the + 比较级",
    ],
    "formula": "so + 形/副 + that ｜ such + 名词 + that ｜ too + adj + to do（太…而不能）",
    "mnemonic": "「so 后形副 such 后名，too…to 否定听」",
    "tips": ["not...until：直到…才（主句动词一般是短暂性动词）"],
    "table": [
        {"cat": "结果 / 程度句型", "items": [
            ["so + adj./adv. + that", "如此…以至于"],
            ["such + (a) + n. + that", "如此…以至于"],
            ["too + adj. + to do", "太…而不能"],
            ["adj. + enough to do", "足够…能做"],
            ["so that", "以便；结果"],
        ]},
        {"cat": "并列句型", "items": [
            ["both...and", "…和…都（谓语复数）"],
            ["either...or", "要么…要么（就近）"],
            ["neither...nor", "既不…也不（就近）"],
            ["not only...but also", "不仅…而且（就近）"],
            ["not...but", "不是…而是"],
        ]},
        {"cat": "It 句型", "items": [
            ["It is + adj. + for sb. to do", "对某人来说做…如何"],
            ["It is + adj. + of sb. to do", "某人做…真…（品质类形容词）"],
            ["It takes sb. time to do", "花某人时间做"],
            ["It is said that...", "据说"],
            ["find it + adj. + to do", "发现做…如何"],
        ]},
        {"cat": "时间 / 条件句型", "items": [
            ["not...until", "直到…才"],
            ["as soon as", "一…就…"],
            ["hardly...when", "刚…就…"],
            ["祈使句 + and/or + 句子", "做…那么/否则"],
        ]},
        {"cat": "比较句型", "items": [
            ["as + adj. + as", "和…一样"],
            ["not so/as...as", "不如…"],
            ["the + 比较级, the + 比较级", "越…越…"],
            ["比较级 + and + 比较级", "越来越…"],
        ]},
    ],
}
